build:
  nodes:
    coverage:
      tests:
        override:
        - command: 'php ./vendor/bin/phpunit --coverage-clover=coverage-clover'
          coverage:
            file: clover.xml
            format: clover